import { STATE_SLICE_KEY } from "./constants";

export const LOAD_SHAPES_REQUEST = `${STATE_SLICE_KEY}/LOAD_SHAPES_REQUEST`;
export const LOAD_SHAPES_SUCCESS = `${STATE_SLICE_KEY}/LOAD_SHAPES_SUCCESS`;
export const LOAD_SHAPES_FAILURE = `${STATE_SLICE_KEY}/LOAD_SHAPES_FAILURE`;
